export const PRIMARY = 'primary';
export const DANGER = 'danger';
export const WARNING = 'warning';
export const TITLE = 'title';
export const SUBTITLE = 'subtitle';
export const TEXT = 'text';
export const AVATAR = 'avatar';
export const COMMENTS_URL =
    'https://jsonplaceholder.typicode.com/comments?_limit=42';
export const AVATAR_SIZE = 1000000;
